name: Bug Report
description: Report a non-security sensitive bug in Remsfal
labels: ["kind/bug", "status/triage"]
body:
  - type: checkboxes
    attributes:
      label: Before reporting an issue
      description: |
        Please search to see if the issue is already reported, and try to reproduce the issue on the latest version of the project.

        Any reported bugs must be reproducible in the latest versions of the Remsfal-repositories.

        **Failing to follow these guidelines may result in your issue being closed without action. ⚠️**
      options:
        - label: I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.
          required: true
  # This is removed since this template is for backend and frontend issues. The List would be unreasonably long and difficult to maintain.
  #- type: dropdown
  #  id: area
  #  attributes:
  #    label: Area
  #    description: Affected area
  #    options:
  #      -
  #      # TODO
  #  validations:
  #    required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of what the problem is.
    validations:
      required: true
  - type: checkboxes
    id: regression
    attributes:
      label: Regression
      description: Was the issue introduced only after upgrading Remsfal, and it worked as expected in the past?
      options:
        - label: The issue is a regression
  - type: textarea
    id: behaviorExpected
    attributes:
      label: Expected behavior
      description: Describe the expected behavior clearly and concisely.
    validations:
      required: true
  - type: textarea
    id: behaviorActual
    attributes:
      label: Actual behavior
      description: Describe the actual behavior clearly and concisely.
    validations:
      required: true
  - type: textarea
    id: reproducer
    attributes:
      label: How to Reproduce?
      description: Provide clear and concise steps to reproduce the problem.
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Anything else?
      description: Links? References? Anything that will give us more context about the issue you are encountering!
    validations:
      required: false
